### ISSUE TITLE
Some help please! Can’t install cydia

### ISSUE THREAD

**Issue by corejita** [asineth0/checkn1x#11]
![4CED3466-E0A3-45E4-B772-306423456977](https://user-images.githubusercontent.com/75546928/101265857-4c2c2080-374a-11eb-8ed1-66b154d0931c.png)

All the computer process perfect, but when im going to install cydia it appears that!

**Comment by corejita** [comment]
Im on IOS 14.2 my device is an IPhone 7 Plus

**Comment by asineth0** [comment]
This isn't a checkn1x issue, it's a checkra1n one.

All I can suggest is restoring your device's firmware in DFU mode with iTunes. You can find a guide on Google for that.

**Comment by corejita** [comment]
Ok thanks!
