### ISSUE TITLE
Package built from the latest 'edge' branch does not work

### ISSUE THREAD

**Issue by dzrdmwjx** [asineth0/checkn1x#14]
checkn1x package built from the latest 'edge' branch does not work.
It doesn't even detect an iDevice connected to a USB port.

To fix it, I updated build.sh to build from the latest stable branch and only install the usbmuxd and its dependencies from 'edge'
Just wanted to give you a heads up as you might run into this issue when checkra1n is updated to the next version

**Comment by asineth0** [comment]
Fixed in [1.1.6](https://github.com/asineth0/checkn1x/releases/tag/1.1.6).
