### ISSUE TITLE
iPhone not recognized 

### ISSUE THREAD

**Issue by r03n-d** [asineth0/checkn1x#16]
This version drops the usb connection as soon as checkra1n loads. GRUB also throws some error codes while loading, see image:
![9AC6BA6F-A959-48CD-9411-4EBE0BA16EAF](https://user-images.githubusercontent.com/41006557/103454608-201ea380-4ce6-11eb-851e-6c659c8e2dea.jpeg)
Changing USB port doesn’t help, and the usb cable is not faulty. This problem does not exist with your previous build, but since I’ve got an A10 the previous build is not working. 
 
iPhone 7+, iOS 14.3

**Comment by hocy1609** [comment]
Same problem, iPhone 7+, iOS 14.3

**Comment by StrangePeanut** [comment]
Same here. iPhone 7 GSM

**Comment by Emanuele-1998** [comment]
Same with iphone 6s

**Comment by ShadyWhite** [comment]
Same issue,iPhone X,iOS 13.5

**Comment by asineth0** [comment]
Fixed in [1.1.6](https://github.com/asineth0/checkn1x/releases/tag/1.1.6).
