### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by denali24s** [asineth0/checkn1x#18]
Hello, I have been using checkn1x version 1.1.4 on iPhone 8 Plus iOS 14.2 and I noticed a new version of checkn1x 1.1.6 I have tried to rejailbreak using the the same method as for version 1.1.4 using windows booting off usb and then selected the A11 passcode bypass and will not work? Is anyone else having issues? Please advise Thank you

**Comment by someivn** [comment]
you should't use checkra1x 1.1.6. it will cause a passcode error. 14.2 or 14.3 using 1.1.4 will be jailbreakable. using checkra1x when there is an error safemode will respring the loop. I recommend using odyssey1x to install odyssey. Hope that can help you.

**Comment by asineth0** [comment]
I'll look into it but I doubt the passcode error is checkn1x related, instead I'd blame checkra1n. 
Odysseyra1n on the latest builds works fine even on iOS 14.
