### ISSUE TITLE
Checknix boots to second monitor

### ISSUE THREAD

**Issue by okumam** [asineth0/checkn1x#19]
I have two monitors: main is an ultrawide, the second is a standard 1080p monitor in portrait orientation.  When I use checknix usb to boot my windows 10 machine, it shows up on the second monitor.  Since that monitor is sideways, it is difficult to read and work with the tool.

Is it not using my main monitor because it is ultrawide?  Or does it simply not know which one is main, and just happens to use the "wrong" one?  

Is there a way to make the tool use the main instead of the secondary?

**Comment by Games-Crack** [comment]
Its possible to do, but the effort is not worth it because you would have to build checknix yourself and edit some config files (btw, this all needs to be done under another Linux system) 

or

 You could try tinkering with your bios/uefi in that way I was able to do it

**Comment by okumam** [comment]
Can you share what you did in your bios settings?  I can look for something similar then.

**Comment by vladaad** [comment]
You should change around the display ports to see if that makes any difference, usually the main one is the one that the BIOS defaults to when you enter it. If that doesn't work I wouldn't bother since you don't really use checkn1x for long periods of time

**Comment by asineth0** [comment]
Can you specify what hardware you're using?
