### ISSUE TITLE
can't open checkra1n through 60% keyboard

### ISSUE THREAD

**Issue by whataprologue** [asineth0/checkn1x#22]
hi, i was trying checkn1x but right after i enter bios i cant open checkra1n with alt+f2 with 60% keyboard, any solution?

**Comment by asineth0** [comment]
don't know your specific keyboard & can't help much. try using your `fn` key.

**Comment by whataprologue** [comment]
im using rk61 60% keyboard, and i already tried using fn alt+f2 still no luck

**Comment by asineth0** [comment]
Not much I can do. Here's the manual for your keyboard though, see if that helps.

https://imgur.com/gallery/pjW8Ts6
