### ISSUE TITLE
An error occurred while executing the command

### ISSUE THREAD

**Issue by esf5021314** [asineth0/checkn1x#25]
chroot rootfs /usr/bin/env PATH=/usr/bin:/bin:/usr/sbin:/sbin \
/sbin/mkinitfs -F "checkn1x" -k -t /tmp -q $(ls rootfs/lib/modules)

The following error occurs when executing the above command

cpio: --no-auto-root Do not automatically prefix input ELFs with ROOT: No such file or directory

I have this error in Centos and Ubuntu. How can I solve it?

**Comment by asineth0** [comment]
Please include the full build script output (use Pastebin/etc). You can do that like this:

```sh
sudo ./build.sh 2>&1 >debug.log
```

**Comment by esf5021314** [comment]
[root@localhost ~]# sudo /root/build.sh 2>&1 >debug.log
cpio:   --no-auto-root  Do not automatically prefix input ELFs with ROOT: No such file or directory
rootfs/lib/modules/5.4.84-0-lts/kernel/drivers/hid/hid-apple.ko (1/1)
  100 %          3,644 B / 18.8 KiB = 0.190                                    
rootfs/lib/modules/5.4.84-0-lts/kernel/drivers/hid/hid-cherry.ko (1/1)
  100 %           1,604 B / 8,032 B = 0.200                                    
rootfs/lib/modules/5.4.84-0-lts/kernel/drivers/hid/hid-generic.ko (1/1)
  100 %           1,296 B / 6,592 B = 0.197                                    
[debug.log](https://github.com/asineth0/checkn1x/files/5968319/debug.log)


This error will still be reported in the terminal, but this error has not been found in the diary file. Does this work properly?

**Comment by esf5021314** [comment]
full log file (copy from terminal)
[log.txt](https://github.com/asineth0/checkn1x/files/5968446/log.txt)

**Comment by asineth0** [comment]
I don't see any issue with the build. I'll look into it more.

**Comment by esf5021314** [comment]
Ok, looking forward to your update
