### ISSUE TITLE
Checknix 1.1.6 passcode state

### ISSUE THREAD

**Issue by jfreeze21** [asineth0/checkn1x#26]
Good pal
I try using checkn1x to reactive my checkrain on iphone X but while i try it at checkra1n and check all the option unsupport, safe, and everything, returning to do the step for the jailbreak, appear error passcode state -17
Can you help me why this happen?... 
thanks a lot for ya time and work
Regards

**Comment by asineth0** [comment]
Please read:

https://checkra.in/news/2020/09/iOS-14-announcement
https://twitter.com/checkra1n/status/1325503723553091585?s=21

This is not a checkn1x issue but rather the current state of checkra1n.

**Comment by asineth0** [comment]
If the above doesn't match your situation, reply with more specific information like your iOS version and such and I can re-open the issue.
