### ISSUE TITLE
Unable to jailbreak iphone 8 on ios 14.4.1 even with skip a11 BPR check, and allow untested devices checked.

### ISSUE THREAD

**Issue by joshn77** [asineth0/checkn1x#28]

**Comment by ajdarius** [comment]
I used checkn1x 1.1.4 version and it worked.

**Comment by NinaPepega** [comment]
I have iphone x 14.4.2 and it doesn't work used versions from 1.1.6-1.1.3 nothing some would work on cli and say checkmate but it wouldn't boot.

**Comment by asineth0** [comment]
Not a checkn1x issue, most likely an issue with upstream checkra1n.

**Comment by ajdarius** [comment]
> Not a checkn1x issue, most likely an issue with upstream checkra1n.

I think we all know, I mentioned that version of checkn1x because it's checkra1n 0.12.1 and it's the solution.

**Comment by joshn77** [comment]
Thanks, imma try another version of checkn1x.
