### ISSUE TITLE
iOS 14.5 checkr1n iPhone 8 global not supported plz add iPhone 8 global

### ISSUE THREAD

**Issue by faheem123456** [asineth0/checkn1x#33]
iOS 14.5 checkr1n iPhone 8 global not supported plz add iPhone 8 global

_Originally posted by @faheem123456 in https://github.com/asineth0/checkn1x/issues/31#issuecomment-830873619_

**Comment by asineth0** [comment]
Not a checkn1x issue, related to upstream checkra1n though.
