### ISSUE TITLE
This version cannot be booted with UEFI

### ISSUE THREAD

**Issue by esf5021314** [asineth0/checkn1x#39]
By the way, how do I make a UEFI bootable image?

**Comment by esf5021314** [comment]
哦对了,这个错误还是有,但是好像不影响正常使用,我应该无视这个错误吗?
cpio: --no-auto-root Do not automatically prefix input ELFs with ROOT: No such file or directory

**Comment by esf5021314** [comment]
Oh, by the way, this error still exists, but it doesn't seem to affect normal use. Should I ignore this error?
cpio: --no-auto-root Do not automatically prefix input ELFs with ROOT: No such file or directory

**Comment by asineth0** [comment]
The `cpio` error is fine.

Also, it boots just fine on UEFI systems. You probably have secure boot on.

```
qemu-system-x86_64 -nodefaults -M q35,accel=kvm -cpu host -m 512 -bios /usr/share/ovmf/x64/OVMF_CODE.fd -cdrom checkn1x-1.1.7.iso
```

**Comment by esf5021314** [comment]
Okay, received, thank you, then I should use UEFI booted Ubuntu to generate the IOS image
