### ISSUE TITLE
Can't access Checkra1n

### ISSUE THREAD

**Issue by ankeongonthe** [asineth0/checkn1x#4]
I use Ether to create USB Boot but when i boot to checkn1x , I can't press Alt+F2 it only shows special characters such as' [d] 24 ~ and disappears soon after

**Comment by CTRL-ALT-EXIST** [comment]
Are you on laptop or desktop?

**Comment by greg97294** [comment]
i had the same issue, i plugged an external usb keyboard to my laptop to fix that

**Comment by idkmicel** [comment]
I have the same issue, still dont know how to fix it and I do not have an external keyboard to use

**Comment by asineth0** [comment]
Try Control+Alt+F2 instead of Alt+F2.

**Comment by idkmicel** [comment]
I figured it out yesterday it is actually fn+alt+f2, I’m pretty sure this
was just a Lenovo thing as I seemed to be one of the few people with this
issue, I appreciate it though!

**Comment by asineth0** [comment]
Ah that makes sense. Some laptop OEMs treat F1-F12 differently instead of sending them normally. I'll add a FAQ with this somewhere.
