### ISSUE TITLE
About the method of dual-boot image generation

### ISSUE THREAD

**Issue by esf5021314** [asineth0/checkn1x#41]
Hello author, I need to generate a dual boot image of uefi+bios. How can I do it? I only successfully generated a mirror that supports bios boot in Ubuntu in uefi mode.

**Comment by esf5021314** [comment]
The 1.1.6 version is compared with the 1.1.7 version. The I386-EFI folder is missing in the grub directory of the 1.1.7 version. How can I generate this folder together?

**Comment by asineth0** [comment]
The images boot on BIOS & UEFI already.
