### ISSUE TITLE
non system disk or disk error replace and strike any key when ready

### ISSUE THREAD

**Issue by AmedGMR47** [asineth0/checkn1x#43]
SOMEONE HELP I USED CHECKN1X AND NOW MY COMPUTER IS BROKEN IT SAYS non system disk or disk error replace and strike any key when ready SOMEONE HELP

**Comment by imomao** [comment]
> SOMEONE HELP I USED CHECKN1X AND NOW MY COMPUTER IS BROKEN IT SAYS non system disk or disk error replace and strike any key when ready SOMEONE HELP

did you figure it out?

**Comment by asineth0** [comment]
Not a checkn1x issue, most likely an issue with your USB or BIOS or tool you used to make the USB. Try Etcher.
