### ISSUE TITLE
Flash failed | balenaEtcher

### ISSUE THREAD

**Issue by newolonos** [asineth0/checkn1x#45]
Etcher sometimes created two, sometimes three partitions for no reason, and it ended up with "Flash failed". No problem code, nothing. Just used Rufus to flash my Stick, and it worked.🤷‍♂️

**Comment by asineth0** [comment]
Probably a bug with Etcher, or an unreliable USB.

**Comment by asineth0** [comment]
If you have a solution or suggestion for me to try to improve compat, let me know. Going to close this for now though. Try Rufus w/ DD mode if you need another option.
