### ISSUE TITLE
Missing productType?

### ISSUE THREAD

**Issue by LunaForeverr** [asineth0/checkn1x#47]
I'm using an iPhone X on 14.6 with Allow Untested iOS Options and Skip A11 BPR check enabled. Face ID and my Passcode is also disabled. I have previously been able to jailbreak my iPhone X on checkn1x with no issues, however when I loaded checkn1x on a new USB stick since I lost my old USB stick with checkn1x loaded on it, it just shows me a Missing productType error when checkn1x boots my iPhone X into Recovery Mode, also telling me to boot my iPhone X into Normal mode when I start the process on Normal mode. Any way to fix this? Thanks.

**Comment by asineth0** [comment]
Not a checkn1x issue, so nothing I can do. Sorry.

https://checkra.in/news/2020/09/iOS-14-announcement
