### ISSUE TITLE
Jailbreak does nothing

### ISSUE THREAD

**Issue by JoshAtticus** [asineth0/checkn1x#54]
I have tried running the jailbreak in normal mode (Alt+F2) multiple times however on reboot, nothing appears. I have an iPhone 6 running iOS 12.5.5.

**Comment by satchnut** [comment]
I have a similar device and sadly, the last version that should work with some finagling (1.0.4) seems to be wiped off the face of the web. As a substitute, search github for bootra1n iso ver 10.1 and follow these steps…

Boot up bootra1n, login, and start checkra1n.
Enable all options in the GUI.
Start the jailbreak process.
When it gets to the “trigger” step, wait 20 sec, then unplug the iPhone. 
Wait 6 seconds, then plug the iPhone back in. 
The iPhone then *should* boot into a state where you can tap the checkra1n app that appears on your homescreen, and you should be good to go. 

These steps worked after a lot of trial and error on my iPad mini 2, 12.5.5. Hopefully it will work for others.

**Comment by JoshAtticus** [comment]
> I have a similar device and sadly, the last version that should work with some finagling (1.0.4) seems to be wiped off the face of the web. As a substitute, search github for bootra1n iso ver 10.1 and follow these steps…
> 
> Boot up bootra1n, login, and start checkra1n. Enable all options in the GUI. Start the jailbreak process. When it gets to the “trigger” step, wait 20 sec, then unplug the iPhone. Wait 6 seconds, then plug the iPhone back in. The iPhone then _should_ boot into a state where you can tap the checkra1n app that appears on your homescreen, and you should be good to go.
> 
> These steps worked after a lot of trial and error on my iPad mini 2, 12.5.5. Hopefully it will work for others.

Hi! Sorry for late reply, thank you SO much for your answer, it really helped.
