### ISSUE TITLE
Grub Error

### ISSUE THREAD

**Issue by Goofychex** [asineth0/checkn1x#55]
I get a _Grub_ error when booting the USB Flash Drive.

- I'm flashing the image with **Rufus.**

The error is: "Unknown file system"
> grub:

**Comment by Goofychex** [comment]
I haven’t had any problems before.
I had a _Linux_ operating system on the Flash Drive, but before flashing the **“checkn1x”** i formatted the drive.

**Comment by vasileioskorompilias** [comment]
Had the same problem. When Rufus asks you whether to write it in ISO or DD mode, choose DD. I also changed the Partition Sheme option from MBR to GPT, and it worked.

**Comment by asineth0** [comment]
Use Rufus in DD mode.
