### ISSUE TITLE
Iphone 8 (Global) 14.7.1 not working

### ISSUE THREAD

**Issue by actuallydot** [asineth0/checkn1x#56]
it just stops me from jailbreaking.

**Comment by JoshAtticus** [comment]
> it just stops me from jailbreaking.

Make sure you turn on "Skip A11 BPR check"

**Comment by prtlw** [comment]
I did that but now I got a Mac so :/

**Comment by asineth0** [comment]
https://checkra.in/news/2020/09/iOS-14-announcement
