### ISSUE TITLE
iPhone 7 ios 15 stuck on "Right before trigger (this is the real bug setup)" checkn1x 1.1.7

### ISSUE THREAD

**Issue by ashotash2000** [asineth0/checkn1x#57]
iPhone 7 gets stuck on "Right before trigger (this is the real bug setup)" and even when waiting for a long time nothing happens. Also I checked the box "unsupported ios version" also i tried to repeat it with checking "verseboot" and "safemode". Hope someone will help me on this!.  I tried it many times before with different ios it worked good. Thanks...

**Comment by DidoGamingYT** [comment]
Checkra1n doesnt work on iOS 15.

**Comment by JoshAtticus** [comment]
> iPhone 7 gets stuck on "Right before trigger (this is the real bug setup)" and even when waiting for a long time nothing happens. Also I checked the box "unsupported ios version" also i tried to repeat it with checking "verseboot" and "safemode". Hope someone will help me on this!. I tried it many times before with different ios it worked good. Thanks...

You cannot jailbreak iOS 15

**Comment by asineth0** [comment]
iOS 15 doesn't work with checkra1n at the moment. Not checkn1x-specific.
