### ISSUE TITLE
passible boot 32bit machine?

### ISSUE THREAD

**Issue by Jar01** [asineth0/checkn1x#6]
i cant boot on 32bit machine, help

**Comment by asineth0** [comment]
checkn1x is currently only built for x86_64. I will add build scripts for i686.

**Comment by Jar01** [comment]
nice, thank u

**Comment by asdfugil** [comment]
> checkn1x is currently only built for x86_64. I will add build scripts for i686.

alpine and checkra1n works down to i486, so that will be i486
