### ISSUE TITLE
Iphone X Ios 15.3.1 checkra1n crash

### ISSUE THREAD

**Issue by Ivyxr** [asineth0/checkn1x#61]
Whenever I load up checkn1x through my usb and go to checkra1n, Everything is fine until I press "Skip A11 BPR check"  It crashes im not sure whether the OS crashes or checkra1n crashes but i'm going to be stuck there until I hard reset my pc.

Any solutions?

**Comment by Ivyxr** [comment]
I found out that whenever I go into settings turn on A11 BPR check go back, go settings, do nothing and go back, then go back and turn on untested versions if needed.

**Comment by JoshAtticus** [comment]
> I found out that whenever I go into settings turn on A11 BPR check go back, go settings, do nothing and go back, then go back and turn on untested versions if needed.

There is no iOS 15 jailbreak
