### ISSUE TITLE
Stuck after checking Skip A11

### ISSUE THREAD

**Issue by alian2plus** [asineth0/checkn1x#62]
I can’t start the jailbreak on 1.1.7 because whenever i check Skip A11 option and get back to start jailbreak it gets stuck and I can’t do anything but to restart the system and so on.

**Comment by JoshAtticus** [comment]
Could you please tell me your iPhone and iOS version?

checkra1n (the program that checkn1x uses) only supports iPhone 5s - iPhone 8/8P/X on iOS 12.0 to 14.8.
**There is no iOS 15/16 jailbreak!**

**Comment by alian2plus** [comment]
iPhone 8 plus iOS 14.4.2

**Comment by JoshAtticus** [comment]
> iPhone 8 plus iOS 14.4.2

Make sure you are not using any form of USB-C connections, as they will not work.

**Comment by alian2plus** [comment]
odysseyn1x Worked fine but yours.

I don’t use c-type cable and only use the one which comes with it.

so I’m just keeping it up to you that your tool has an issue , just in case someone else would have the issue as mine.

thank you so much for the hard work.

**Comment by alian2plus** [comment]
Feel free to close this ticket.
