### ISSUE TITLE
build.sh having issues

### ISSUE THREAD

**Issue by mymegagear** [asineth0/checkn1x#63]
i get unsigned errors for repositories
the result file doesn't work.

tried editing script but couldn't get it output a working .iso
i need to use checkra1n 0.12.3 because other versions don't work quite well.
I noticed 0.12.3 isn't in the compiled releases and i've tried the other checkn1x versions
but they stop or give errors after iphone is placed on DFU.  This is for an iphone 7  on ios 13
however in ubuntu using checkra1n 0.12.3 works well on this phone using CLI.
I'd like to see a checkn1x version

Thank you for taking time to read.

**Comment by asineth0** [comment]
I don't really maintain this anymore. If you fix it, I'll merge a PR.
