### ISSUE TITLE
Selected boot image did not Authenticate.

### ISSUE THREAD

**Issue by kiwi311** [asineth0/checkn1x#65]
Ive tried it on multiple pc's with multiple usb-sticks and with 2 differned programms (rufus & Etcher) it wont work.
My system just wont boot this image.
"Selected boot image did not Authenticate."
or 
"Operating System Loader failed signature verification. WARNING: The file may have been tampered! All bootable devices failed Secure Boot verivication"
please Help

**Comment by asineth0** [comment]
Disable Secure Boot in your UEFI settings.

**Comment by kiwi311** [comment]
Thanks ! That helped but I just found out (a little bit late) that IOS14.6 is not working.. is this coming soon for it to, can I downgrade my IOS to 14.X or do I have to buy a different phone ?

**Comment by kiwi311** [comment]
> Disable Secure Boot in your UEFI settings.
Thanks ! That helped but I just found out (a little bit late) that IOS14.6 is not working.. is this coming soon for it to, can I downgrade my IOS to 14.X or do I have to buy a different phone ?

**Comment by asineth0** [comment]
You should probably read about checkra1n & iOS 14: https://checkra.in/news/2020/09/iOS-14-announcement
