### ISSUE TITLE
ancient

### ISSUE THREAD

**Issue by alexmutex** [asineth0/checkn1x#66]
the dinosaurs called they want their checn1x back

**Comment by asineth0** [comment]
Do you need me to fix something?

**Comment by NanashiTheNameless** [comment]
checkn1x literally has the latest official checkra1n, there is no reason to update until that releases a new version

**Comment by alexmutex** [comment]
i was making a joke jeez

**Comment by NanashiTheNameless** [comment]
> i was making a joke jeez

Let me teach you a lesson in professionalism, don't waste developers time with bad jokes, especially when they aren't funny and have nothing to do with the project, also GitHub Issues is NOT the place to do it...

**Comment by alexmutex** [comment]
🤓
