### ISSUE TITLE
Get stuck when booting using laptop

### ISSUE THREAD

**Issue by ninhhv0012** [asineth0/checkn1x#70]
When I restart the laptop and enter the jailbreak boot. The screen just show message and do nothing
![Screenshot 2024-06-15 155738](https://github.com/asineth0/checkn1x/assets/159209373/9050878e-6db4-4a7b-b95e-902330dfcda4)

**Comment by NanashiTheNameless** [comment]
You are on an outdated version, try upgrading before you raise such a "bugreport"
https://github.com/asineth0/checkn1x/releases/latest

**Comment by ninhhv0012** [comment]
> You are on an outdated version, try upgrading before you raise such a "bugreport" https://github.com/asineth0/checkn1x/releases/latest

I tried version 1.1.7 but I still got error

**Comment by Ashhxoops** [comment]
Same here. I keep getting an unknown filesystem error

**Comment by asineth0** [comment]
use Etcher to make the USB, some tools for making bootable USBs do weird things to the drive instead of directly copying the imagine onto the drive at a block-level.
