### ISSUE TITLE
check_snapshot_error_code: General

### ISSUE THREAD

**Issue by radarwall224** [asineth0/checkn1x#8]
iget error trying to install cydia
iphone 8 plus global ios 14.1

**Comment by asineth0** [comment]
That's most likely an issue with checkra1n, not checkn1x. Try restoring device in DFU mode with iTunes/idevicerestore.

**Comment by Dark42ed** [comment]
Are you able to send the error?

**Comment by radarwall224** [comment]
After I ran I cloud bypass tool I ran checkn1x again and no more error. Just want to say nice work chrckn1x only jailbreak method that work on all my device thank u

**Comment by Dark42ed** [comment]
Please close this issue if you have resolved your problem.
