### ISSUE TITLE
How would one open into checkra1n after booting on to the iso

### ISSUE THREAD

**Issue by trudruchocolatemilk** [asineth0/checkn1x#9]

**Comment by trudruchocolatemilk** [comment]
oops never mind it worked, i was using rufus and not etcher, so you could say that rufus isnt supported

**Comment by Dark42ed** [comment]
Please close this issue if you have resolved your problem.

**Comment by asdfugil** [comment]
> oops never mind it worked, i was using rufus and not etcher, so you could say that rufus isnt supported

it does work in DD mode
